spring:
  application:
    name: neurofit-gateway
  cloud:
    gateway:
      routes:
        - id: keycloak-auth
          uri: http://keycloak:8080
          predicates:
            - Path=/realms/neurofit/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: neurofit-gateway
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/neurofit
            authorization-uri: http://localhost:8081/realms/neurofit/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/neurofit/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/neurofit/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/neurofit/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/neurofit

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health