spring:
  application:
    name: neurofit-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      server:
        webflux:
          routes:
            - id: keycloak-login
              uri: http://keycloak:8080
              predicates:
                - Path=/login
              filters:
                - SetPath=/realms/neurofit/protocol/openid-connect/auth
            - id: keycloak-register
              uri: http://keycloak:8080
              predicates:
                - Path=/register
              filters:
                - SetPath=/realms/neurofit/protocol/openid-connect/registrations
            - id: keycloak-auth
              uri: http://keycloak:8080
              predicates:
                - Path=/realms/neurofit/**
              filters:
                - RewritePath=/realms/(?<realm>[^/]+)/(?<remaining>.*), /realms/${realm}/${remaining}
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health