spring:
  application:
    name: neurofit-gateway
  cloud:
    gateway:
      routes:
#        - id: keycloak-login
#          uri: http://keycloak:8080
#          predicates:
#            - Path=/login
#          filters:
#            - Need to fix the login still
        - id: keycloak-register
          uri: http://keycloak:8080
          predicates:
            - Path=/register
          filters:
            - RedirectTo=302, http://localhost:8081/realms/neurofit/protocol/openid-connect/registrations?client_id=neurofit-gateway
        - id: keycloak-auth
          uri: http://keycloak:8080
          predicates:
            - Path=/realms/neurofit/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/neurofit

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health