spring:
  application:
    name: neurofit-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${your-keycloak-url}/realms/neurofit-test